---
deployment:
  tasks:
    - cd ../../restful.pratikwadekar.me/ && rm *.js && rm *.html && rm *.css && rm *.txt && rm *.ico && rm -r assets && /bin/cp -R ../repositories/restful-api-request-builder/dist/restful-builder/* ../../../../restful.pratikwadekar.me
